#define GLIB_DISABLE_DEPRECATION_WARNINGS
#include <cairo.h>
#include <cairo-deprecated.h>
#include <cairo-features.h>
#include <cairo-ft.h>
#include <cairo-gobject.h>
#include <cairo-pdf.h>
#include <cairo-ps.h>
#include <cairo-quartz-image.h>
#include <cairo-quartz.h>
#include <cairo-script-interpreter.h>
#include <cairo-script.h>
#include <cairo-svg.h>
#include <cairo-tee.h>
#include <cairo-version.h>
